const assert = require('node:assert/strict');
const vscode = require('vscode');
const fs = require('node:fs');
const path = require('node:path');
const id='assembly-convention-checker.assembly-convention-checker';
const delay = ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(predicate,label) {
  for(let attempt=0;attempt<150;attempt++){if(predicate())return;await delay(100);}
  throw new Error(`Timed out: ${label}`);
}
exports.run = async () => {
  const extension=vscode.extensions.getExtension(id);
  assert.ok(extension,'Extension is installed in test host');
  const controller=await extension.activate();
  let reportReady=false;
  const receive=controller.receive.bind(controller);
  controller.receive=message=>{if(message?.type==='ready')reportReady=true;return receive(message);};
  const config=vscode.workspace.getConfiguration('assemblyConventionChecker');
  await config.update('runOn','change',vscode.ConfigurationTarget.Workspace);
  const source=vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri,'sample.s');
  const doc=await vscode.workspace.openTextDocument(source);
  const editor=await vscode.window.showTextDocument(doc);
  await vscode.commands.executeCommand('assemblyConventionChecker.analyze');
  assert.equal(controller.getSnapshot(source.toString()).state,'ready');
  assert.equal(vscode.languages.getDiagnostics(source).length,0);
  await editor.edit(edit=>edit.replace(new vscode.Range(0,0,doc.lineCount,0),'.globl sample\nsample: testq %rdi,%rdi; je 1f; std\n1: ret\n'));
  await vscode.commands.executeCommand('assemblyConventionChecker.analyze');
  assert.ok(vscode.languages.getDiagnostics(source).some(d=>d.severity===vscode.DiagnosticSeverity.Warning));
  assert.ok(vscode.languages.getDiagnostics(source).some(d=>d.severity===vscode.DiagnosticSeverity.Information));
  await editor.edit(edit=>edit.replace(new vscode.Range(0,0,doc.lineCount,0),'.globl sample\nsample: call helper\nstd\nret\n'));
  assert.equal(controller.getSnapshot(source.toString()).state,'loading');
  assert.ok(controller.getSnapshot(source.toString()).report,'Prior report layout is preserved while updating');
  await until(()=>vscode.languages.getDiagnostics(source).some(d=>d.code==='ABI_STACK_ALIGNMENT'),'live unsaved diagnostics');
  assert.equal(doc.isDirty,true);
  const diagnostics=vscode.languages.getDiagnostics(source);
  assert.ok(diagnostics.some(d=>d.code==='ABI_DIRECTION_FLAG' && d.severity===vscode.DiagnosticSeverity.Error));
  assert.ok(diagnostics.some(d=>d.message.includes('Suggestion:')));
  const snapshot=controller.getSnapshot(source.toString());
  assert.equal(snapshot.version,doc.version); assert.ok(snapshot.report.complete);
  await vscode.commands.executeCommand('assemblyConventionChecker.openReport');
  await until(()=>reportReady,'webview assets load and execute under the real content security policy');
  assert.ok(vscode.window.tabGroups.all.flatMap(group=>group.tabs).some(tab=>tab.label==='Assembly · Convention Report'),'Reusable report tab');
  await vscode.commands.executeCommand('assemblyConventionChecker.openReport');
  assert.equal(vscode.window.tabGroups.all.flatMap(group=>group.tabs).filter(tab=>tab.label==='Assembly · Convention Report').length,1);
  // Exercise the same validated navigation handler that receives webview messages.
  const index=snapshot.report.diagnostics.findIndex(d=>d.rule_id==='ABI_STACK_ALIGNMENT');
  await controller.receive({type:'navigate',kind:'finding',index,uri:source.toString(),version:snapshot.version});
  const target=vscode.window.visibleTextEditors.find(e=>e.document===doc);
  assert.equal(target.selection.start.line,snapshot.report.diagnostics[index].location.line-1);
  const prior=target.selection;
  await controller.receive({type:'navigate',kind:'finding',index,uri:'file:///not-allowed.s',version:snapshot.version});
  assert.ok(target.selection.isEqual(prior),'Forged source URI must be rejected');
  const included=vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri,'included.s');
  fs.writeFileSync(included.fsPath,'helper: ret\n');
  await editor.edit(edit=>edit.replace(new vscode.Range(0,0,doc.lineCount,0),'.include "included.s"\n.globl sample\nsample: subq $8,%rsp; call helper; addq $8,%rsp; ret\n'));
  await vscode.commands.executeCommand('assemblyConventionChecker.analyze');
  assert.deepEqual(controller.getSnapshot(source.toString()).report.functions.map(f=>f.name),['helper','sample']);
  const includedDoc=await vscode.workspace.openTextDocument(included);
  const includedEditor=await vscode.window.showTextDocument(includedDoc);
  await includedEditor.edit(edit=>edit.replace(new vscode.Range(0,0,includedDoc.lineCount,0),'helper: std; ret\n'));
  await until(()=>controller.getSnapshot(source.toString()).state==='ready' && controller.getSnapshot(source.toString()).report.diagnostics.some(d=>d.rule_id==='ABI_DIRECTION_FLAG'),'unsaved include invalidates parent');
  assert.ok(vscode.languages.getDiagnostics(included).some(d=>d.code==='ABI_DIRECTION_FLAG'),'Included findings are published on the included file');
  assert.equal(vscode.languages.getDiagnostics(source).length,0,'Included findings are not placed on the parent source');
  await vscode.window.showTextDocument(doc);
  const includedSnapshot=controller.getSnapshot(source.toString());
  const includedFinding=includedSnapshot.report.diagnostics.findIndex(d=>d.rule_id==='ABI_DIRECTION_FLAG');
  await controller.receive({type:'navigate',kind:'finding',index:includedFinding,uri:source.toString(),version:includedSnapshot.version});
  assert.ok(vscode.window.visibleTextEditors.some(e=>e.document===includedDoc && e.selection.start.line===0),'Report navigation opens the included source');
  const untitled=await vscode.workspace.openTextDocument({content:'.globl other\nother: ret\n',language:'plaintext'});
  await vscode.window.showTextDocument(untitled);
  await vscode.commands.executeCommand('assemblyConventionChecker.analyze');
  assert.equal(controller.getSnapshot(untitled.uri.toString()).report.complete,true,'Manual checking supports untitled text');
  await config.update('runOn','manual',vscode.ConfigurationTarget.Workspace);
  await until(()=>controller.getSnapshot(untitled.uri.toString()).state==='empty','manual settings invalidate old reports');
  await config.update('enabled',false,vscode.ConfigurationTarget.Workspace);
  await until(()=>vscode.languages.getDiagnostics(source).length===0,'disabled clears diagnostics');
  assert.equal(controller.getSnapshot(source.toString()).state,'disabled');
  await config.update('enabled',true,vscode.ConfigurationTarget.Workspace);
  await vscode.window.showTextDocument(doc);
  await vscode.commands.executeCommand('assemblyConventionChecker.analyze');
  assert.equal(controller.getSnapshot(source.toString()).state,'ready');
  const artifact=path.resolve(__dirname,'../../../artifacts/integration-result.json');
  fs.mkdirSync(path.dirname(artifact),{recursive:true});
  fs.writeFileSync(artifact,JSON.stringify({passed:true,extensionPath:extension.extensionPath,checks:['activation','clean buffer','live unsaved errors','all diagnostic severities and suggestion','stable updating layout','document version','report assets and CSP','report reuse','source navigation','forged URI rejection','untitled text','manual mode','disabled diagnostics','reenable','bundled import isolation']},null,2));
  console.log('Extension-host integration checks passed.');
};
